In [ ]:
import numpy as np
import pandas as pd

In [ ]:
data = {
    "A": [1, 2, 3, 4, 5, 6],
    "B": [10, np.nan, 30, 40, np.nan, 60],
    "C": [100, 200, 300, np.nan, 500, 600],
    "D": [7, 8, 9, 10, np.nan, 12],
    "E": [15, np.nan, 17, np.nan, 19, np.nan]
}
df = pd.DataFrame(data) # by default it took datatype as float except column A bcz of no any null value (it works column basis)
df

**CHECKING NULL VALUES (Works Column basis)**

In [7]:
df.isna()

       A      B      C      D      E
0  False  False  False  False  False
1  False   True  False  False   True
2  False  False  False  False  False
3  False  False   True  False   True
4  False   True  False   True  False
5  False  False  False  False   True

In [8]:
df.isna().sum() # Count null values in each column

A    0
B    2
C    1
D    1
E    3
dtype: int64

In [9]:
df.isna().any() #tells kon konsa column ma null values han

A    False
B     True
C     True
D     True
E     True
dtype: bool

**Removing Missing Data (Works ROW basis)**

In [10]:
df.dropna() # ya har us row ko remove kr dega jis ma null values han

   A     B      C    D     E
0  1  10.0  100.0  7.0  15.0
2  3  30.0  300.0  9.0  17.0

In [15]:
# We can set a threshold or limit to check n number of not null values like if i set 
# theshold to 4, them it must force you to extract those rows which has atleast  4 non null values
df.dropna(thresh=4)

   A     B      C     D     E
0  1  10.0  100.0   7.0  15.0
2  3  30.0  300.0   9.0  17.0
5  6  60.0  600.0  12.0   NaN

**FILLING THE MISSING DATA (Works Column wise)**

In [22]:
df.fillna(0) # Fill all the NaN values with zero
# We can use custom values in each column
df.fillna({'A' : 10 , 'B' : 20 , 'C' : 30 , 'D':50 , 'E' : 60}) # works columns wise
df.fillna(df.mean()) 
df.fillna(df.median())
#Calculate mean of each column and Replace every NaN in a column with that column's mean.

   A     B      C     D     E
0  1  10.0  100.0   7.0  15.0
1  2  35.0  200.0   8.0  17.0
2  3  30.0  300.0   9.0  17.0
3  4  40.0  300.0  10.0  17.0
4  5  35.0  500.0   9.0  19.0
5  6  60.0  600.0  12.0  17.0

In [25]:
# There is Also Backward Fill (next valid value) and Forward Fill (previous valid value)
print(df)
print(df.bfill())
print(df.ffill())

   A     B      C     D     E
0  1  10.0  100.0   7.0  15.0
1  2   NaN  200.0   8.0   NaN
2  3  30.0  300.0   9.0  17.0
3  4  40.0    NaN  10.0   NaN
4  5   NaN  500.0   NaN  19.0
5  6  60.0  600.0  12.0   NaN
   A     B      C     D     E
0  1  10.0  100.0   7.0  15.0
1  2  30.0  200.0   8.0  17.0
2  3  30.0  300.0   9.0  17.0
3  4  40.0  500.0  10.0  19.0
4  5  60.0  500.0  12.0  19.0
5  6  60.0  600.0  12.0   NaN
   A     B      C     D     E
0  1  10.0  100.0   7.0  15.0
1  2  10.0  200.0   8.0  15.0
2  3  30.0  300.0   9.0  17.0
3  4  40.0  300.0  10.0  17.0
4  5  40.0  500.0  10.0  19.0
5  6  60.0  600.0  12.0  19.0

**For Checking - isna(),**
**For removing - dropna(),**
**For Filling - fillna()**

In [ ]:
# For Checking - isna(), 
# For removing - dropna(), 
# For Filling - fillna()