In [58]:
import numpy as np
import pandas as pd

In [59]:
data = pd.read_csv("sales.csv" , parse_dates=["Date"] , dtype={'PaymentMethod' : "category"})
data.info()
data.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3500 entries, 0 to 3499
Data columns (total 20 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   OrderID         3500 non-null   object
 1   Date            3500 non-null   datetime64[ns]
 2   CustomerName    3500 non-null   object
 3   CustomerEmail   3500 non-null   object
 4   Country         3500 non-null   object
 5   City            3500 non-null   object
 6   Category        3500 non-null   object
 7   Product         3500 non-null   object
 8   Quantity        3500 non-null   int64
 9   UnitPrice       3500 non-null   float64
 10  Subtotal        3500 non-null   float64
 11  DiscountPct     3500 non-null   int64
 12  DiscountAmount  3500 non-null   float64
 13  Tax8Pct         3500 non-null   float64
 14  GrandTotal      3500 non-null   float64
 15  PaymentMethod   3500 non-null   category
 16  ShippingMethod  3500 non-null   object
 17  OrderStatus     3500 non-null   object
 18  SalesRep        3500 non-null   object
 19  Rating          3500 non-null   int64
dtypes: category(1), datetime64[ns](1), float64(5), int64(3), object(10)
memory usage: 523.3+ KB

,OrderID,Date,CustomerName,CustomerEmail,Country,City,Category,Product,Quantity,UnitPrice,Subtotal,DiscountPct,DiscountAmount,Tax8Pct,GrandTotal,PaymentMethod,ShippingMethod,OrderStatus,SalesRep,Rating
0,ORD-10001,2023-01-01,Priya Sharma,customer1987@email.com,UAE,New York,Books,Web Dev,1,47.23,47.23,15,7.08,3.21,43.36,COD,Overnight,Cancelled,Nadia Islam,4
1,ORD-10002,2023-01-01,Sam Wilson,customer7771@email.com,UAE,Sydney,Sports,Gym Bag,9,377.88,3400.92,5,170.05,258.47,3489.34,PayPal,Express,Delivered,Nadia Islam,5
2,ORD-10003,2023-01-01,Kevin Hart,customer2115@email.com,UK,Berlin,Home & Kitchen,Kettle,7,243.58,1705.06,10,170.51,122.76,1657.31,Debit Card,Overnight,Delivered,Usman Khan,5
3,ORD-10004,2023-01-01,Frank Castle,customer4932@email.com,UK,Islamabad,Sports,Yoga Mat,6,112.63,675.78,5,33.79,51.36,693.35,COD,Express,Delivered,Nadia Islam,4
4,ORD-10005,2023-01-01,Frank Castle,customer5434@email.com,UAE,Dubai,Sports,Dumbbells,2,55.73,111.46,15,16.72,7.58,102.32,Bank Transfer,Standard,Cancelled,John Doe,4

# MAP FUNCTION

In [60]:
# Map is used on Pandas series so we can use a single column of Dataframe as a series
data.groupby("PaymentMethod").size()
data["Payment Type"] = data["PaymentMethod"].map({
    "Bank Transfer" : "Physical",
    "COD" : "Physical",
    "Credit Card" : "Digital",
    "Debit Card" : "Digital",
    "PayPal" : "Digital"
})
# It creates new column and fill values according to above given condition like if PayementMethod id Bank Transfer/COD, fill that rows with Physical Payment Type
data.info()
data.head()
data.groupby("Payment Type").size()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3500 entries, 0 to 3499
Data columns (total 21 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   OrderID         3500 non-null   object
 1   Date            3500 non-null   datetime64[ns]
 2   CustomerName    3500 non-null   object
 3   CustomerEmail   3500 non-null   object
 4   Country         3500 non-null   object
 5   City            3500 non-null   object
 6   Category        3500 non-null   object
 7   Product         3500 non-null   object
 8   Quantity        3500 non-null   int64
 9   UnitPrice       3500 non-null   float64
 10  Subtotal        3500 non-null   float64
 11  DiscountPct     3500 non-null   int64
 12  DiscountAmount  3500 non-null   float64
 13  Tax8Pct         3500 non-null   float64
 14  GrandTotal      3500 non-null   float64
 15  PaymentMethod   3500 non-null   category
 16  ShippingMethod  3500 non-null   object
 17  OrderStatus     3500 non-null   object
 18  SalesRep        3500 non-null   object
 19  Rating          3500 non-null   int64
 20  Payment Type    3500 non-null   object
dtypes: category(1), datetime64[ns](1), float64(5), int64(3), object(11)
memory usage: 550.6+ KB

C:\Users\Supreme_Traders\AppData\Local\Temp\ipykernel_23240\1476450372.py:2: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  data.groupby("PaymentMethod").size()

Payment Type
Digital     2776
Physical     724
dtype: int64

In [61]:
data["Payment Type"].unique()
# Before v/s After
data[["PaymentMethod" , "Payment Type"]].head()

   PaymentMethod Payment Type
0            COD     Physical
1         PayPal      Digital
2     Debit Card      Digital
3            COD     Physical
4  Bank Transfer     Physical

# APPLY Operation

In [62]:
def rating_category(data):
    # print(type(data)) -> Always Series
    if data["Rating"] == 5:
        return "Best"
    elif data["Rating"] == 4:
        return "Good"
    elif data["Rating"] == 3:
        return "Average"
    elif data["Rating"] == 2:
        return "Below Average"
    else : return "Bad"
data["Rating Category"] = data.apply(rating_category , axis=1 ) 
# Note if i am apply on sigle column/row then i don't have to mention axis other for entire data i have to mention the axis (1 always other wise error)
# WHY AXIS is 1? : bcz data that i am passing as arrgument is a single row and we are accessing rating column from that row -> row["Rating"]
# Here each row is passing as a series 
'''
OrderID   Rating   GrandTotal
0     ORD-001      5        250.0
1     ORD-002      3        120.0
2     ORD-003      4        390.0

axis=0 → function receives ['ORD-001', 'ORD-002', 'ORD-003']  ← entire column
axis=1 → function receives ['ORD-001', 5, 250.0]              ← entire row
'''
print(data[["Rating" , "Rating Category"]].tail() , end="\n\n")
print(data["Rating Category"].value_counts() , end="\n\n") # Like group by
print(data.groupby("Rating Category")["Rating Category"].count())

      Rating Rating Category
3495       4            Good
3496       5            Best
3497       2   Below Average
3498       5            Best
3499       3         Average

Rating Category
Best             1384
Good             1228
Average           539
Below Average     182
Bad               167
Name: count, dtype: int64

Rating Category
Average           539
Bad               167
Below Average     182
Best             1384
Good             1228
Name: Rating Category, dtype: int64

# PIPE FUNCTION
**pipe = pass the DataFrame into a function, get it back, pass to next function**

**Water → Pipe 1 (Filter) → Pipe 2 (Add Minerals) → Pipe 3 (Cool Down) → Final Water**

**Same in pandas: DataFrame → pipe(add_profit) → pipe(add_net_revenue) → Final DataFrame**

Without pipe — messy
pythondf = add_profit(df)
df = add_net_revenue(df)
df = add_tax(df)
df = add_discount(df)
You keep rewriting df = again and again.

With pipe — clean
pythondf = (
    df
    .pipe(add_profit)
    .pipe(add_net_revenue)
    .pipe(add_tax)
    .pipe(add_discount)
)
Same result, but reads like a step by step recipe — top to bottom.

In [63]:
def add_profit(data):
    data['Profit'] = data['GrandTotal'] * 0.20   # 20% profit margin
    return data

def add_net_revenue(data):
    data['NetRevenue'] = data['GrandTotal'] - data['Profit']
    return data
data = (
    data
    .pipe(add_profit)
    .pipe(add_net_revenue)
)
data.head()

,OrderID,Date,CustomerName,CustomerEmail,Country,City,Category,Product,Quantity,UnitPrice,...,GrandTotal,PaymentMethod,ShippingMethod,OrderStatus,SalesRep,Rating,Payment Type,Rating Category,Profit,NetRevenue
0,ORD-10001,2023-01-01,Priya Sharma,customer1987@email.com,UAE,New York,Books,Web Dev,1,47.23,...,43.36,COD,Overnight,Cancelled,Nadia Islam,4,Physical,Good,8.672,34.688
1,ORD-10002,2023-01-01,Sam Wilson,customer7771@email.com,UAE,Sydney,Sports,Gym Bag,9,377.88,...,3489.34,PayPal,Express,Delivered,Nadia Islam,5,Digital,Best,697.868,2791.472
2,ORD-10003,2023-01-01,Kevin Hart,customer2115@email.com,UK,Berlin,Home & Kitchen,Kettle,7,243.58,...,1657.31,Debit Card,Overnight,Delivered,Usman Khan,5,Digital,Best,331.462,1325.848
3,ORD-10004,2023-01-01,Frank Castle,customer4932@email.com,UK,Islamabad,Sports,Yoga Mat,6,112.63,...,693.35,COD,Express,Delivered,Nadia Islam,4,Physical,Good,138.670,554.680
4,ORD-10005,2023-01-01,Frank Castle,customer5434@email.com,UAE,Dubai,Sports,Dumbbells,2,55.73,...,102.32,Bank Transfer,Standard,Cancelled,John Doe,4,Physical,Good,20.464,81.856