**Merging 2 Dataframes**

In [18]:
import numpy as np
import pandas as pd

In [19]:
names = pd.DataFrame({
    "ID": [1, 2, 3, 4, 5],
    "Name": ["Ali", "Sara", "Ahmed", "Ayesha", "Bilal"],
    "Department": ["IT", "HR", "Finance", "IT", "Marketing"]
})
salaries = pd.DataFrame({
    "ID": [1, 2, 3, 7, 8],
    "Salary": [50000, 60000, 55000, 70000, 65000],
    "Experience": [1, 3, 2, 5, 4]
})

In [10]:
names
salaries

   ID  Salary  Experience
0   1   50000           1
1   2   60000           3
2   3   55000           2
3   7   70000           5
4   8   65000           4

**MERGE(Work same like JOIN in MySQL)**

In [22]:
pd.merge(names , salaries) #Automatically find comman values (ID) to merge but we can also set manually

   ID   Name Department  Salary  Experience
0   1    Ali         IT   50000           1
1   2   Sara         HR   60000           3
2   3  Ahmed    Finance   55000           2

In [21]:
pd.merge(names , salaries , on='ID' , how='inner')
# As in MySQL there is inner, outer , left and right join - but default is inner join but we can change using 'how=' parameter
pd.merge(names ,salaries , on='ID' , how='outer')
pd.merge(names ,salaries , on='ID' , how='left')
pd.merge(names ,salaries , on='ID' , how='right')

   ID   Name Department  Salary  Experience
0   1    Ali         IT   50000           1
1   2   Sara         HR   60000           3
2   3  Ahmed    Finance   55000           2
3   7    NaN        NaN   70000           5
4   8    NaN        NaN   65000           4

**Concatination of 2 Dataframes**

In [24]:
names = pd.DataFrame({
    "ID": [1, 2, 3, 4, 5],
    "Name": ["Ali", "Sara", "Ahmed", "Ayesha", "Bilal"],
    "Department": ["IT", "HR", "Finance", "IT", "Marketing"]
})
salaries = pd.DataFrame({
    "ID": [1, 2, 3, 7, 8],
    "Salary": [50000, 60000, 55000, 70000, 65000],
    "Experience": [1, 3, 2, 5, 4]
})

In [27]:
# pd.concat(names , salaries) # Error bcz concat takes one argument but we have two values so we pass list instead of direct values
pd.concat([names , salaries]) # By default it works column basis - axix 0
# But we can change axis 1 (Row)
pd.concat([names , salaries] , axis=1) #Ro w basis

   ID    Name Department  ID  Salary  Experience
0   1     Ali         IT   1   50000           1
1   2    Sara         HR   2   60000           3
2   3   Ahmed    Finance   3   55000           2
3   4  Ayesha         IT   7   70000           5
4   5   Bilal  Marketing   8   65000           4

**Joining of two dataframes**

In [28]:
A = pd.DataFrame({
    "key": [1, 2, 3, 4],
    "x": [100, 200, 300, 400]
})

b = pd.DataFrame({
    "key": [3, 4, 5, 6],
    "y": [3000, 4000, 5000, 6000]
})

In [35]:
# a.join(b) gets error bcz "JOIN BY DEFAULT WORKS ON INDEX"
# UPDATED DATAFRAMES
a = pd.DataFrame({
    "x": [100, 200, 300, 400]
} , index= [1, 2, 3, 4])

b = pd.DataFrame({
    "y": [3000, 4000, 5000, 6000] 
} , index=[3, 4, 5, 6]) 
print(a.join(b)) # BASICALLY IT IS INNER JOIN
# See the clear difference b/w merge and join. Merge only keeps comman rows values but joins keeps both (with NaN values)
# We Can change by default comparssion values
print(a.join(b , how='outer'))

     x       y
1  100     NaN
2  200     NaN
3  300  3000.0
4  400  4000.0
       x       y
1  100.0     NaN
2  200.0     NaN
3  300.0  3000.0
4  400.0  4000.0
5    NaN  5000.0
6    NaN  6000.0

In [ ]:
# inplace=True means modify the original dataframe directly instead of returning a new one.
# Without inplace — must reassign
df = df.dropna()

# With inplace — modifies df directly, returns None
df.dropna(inplace=True)
# Modern tip: Most pandas developers now prefer the reassignment style (df = df.dropna()) and avoid inplace=True. 
# It's clearer, works better in method chaining, and pandas may deprecate inplace in future versions.